import { builder } from "../../lib/builder";

builder.prismaObject("WeatherData", {
  fields: (t) => ({
    id: t.exposeID("id"),
    observationTime: t.exposeString("observationTime"),
    temperature: t.exposeInt("temperature"),
    weatherCode: t.exposeInt("weatherCode"),
    weatherIcons: t.exposeStringList("weatherIcons"),
    weatherDescriptions: t.exposeStringList("weatherDescriptions"),
    astroSunrise: t.exposeString("astroSunrise"),
    astroSunset: t.exposeString("astroSunset"),
    astroMoonrise: t.exposeString("astroMoonrise"),
    astroMoonset: t.exposeString("astroMoonset"),
    astroMoonPhase: t.exposeString("astroMoonPhase"),
    astroMoonIllumination: t.exposeInt("astroMoonIllumination"),
    airQualityCo: t.exposeFloat("airQualityCo"),
    airQualityNo2: t.exposeFloat("airQualityNo2"),
    airQualityO3: t.exposeFloat("airQualityO3"),
    airQualitySo2: t.exposeFloat("airQualitySo2"),
    airQualityPm25: t.exposeFloat("airQualityPm25"),
    airQualityPm10: t.exposeFloat("airQualityPm10"),
    airQualityUsEpaIndex: t.exposeInt("airQualityUsEpaIndex"),
    airQualityGbDefraIndex: t.exposeInt("airQualityGbDefraIndex"),
    windSpeed: t.exposeInt("windSpeed"),
    windDegree: t.exposeInt("windDegree"),
    windDir: t.exposeString("windDir"),
    pressure: t.exposeInt("pressure"),
    precip: t.exposeInt("precip"),
    humidity: t.exposeInt("humidity"),
    cloudcover: t.exposeInt("cloudcover"),
    feelslike: t.exposeInt("feelslike"),
    uvIndex: t.exposeInt("uvIndex"),
    visibility: t.exposeInt("visibility"),
    createdAt: t.expose("createdAt", { type: "DateTime" }),
    updatedAt: t.expose("updatedAt", { type: "DateTime" }),
    property: t.relation("property", { nullable: true }),
  }),
});
